export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST'
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS'
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL'

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST'
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS'
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL'
